### PR TITLE
waiting_for_mycroft

### LINKED ISSUE #7: new module - waiting_for_mycroft
since PRs are not merged we can provide some alternative imports adding functionality that mycroft refuses/takes forever implementing

this will only work for skills, not core functionality like intents

- provide a subclass for skill gui, users would need to assign this to self.gui in their initialize method
- provide a subclass for common play skill 
	- my alternative skill with [all unmerged PRs](https://github.com/MycroftAI/skill-playback-control/pulls?q=is%3Apr+author%3A%40me+sort%3Aupdated-desc+is%3Aclosed) will replace official skill

Initial improvements to bundle

- https://github.com/MycroftAI/mycroft-core/pull/2698
- https://github.com/MycroftAI/mycroft-core/pull/2660

### PR DESCRIPTION
**Pull request by JarbasAl**
closes #7 

### Fixes

- sync and rename `ovos_utils.intents.IntentApi` to `IntentQueryApi` which was [merged in mycroft-core](https://github.com/MycroftAI/mycroft-core/pull/2468) and diverged
- workaround https://github.com/MycroftAI/mycroft-core/pull/2786 not being merged

### New methods

- add `ovos_utils.resolve_ovos_resource_file`
- add `ovos_utils.lang.get_language_dir` 
	- enables https://github.com/MycroftAI/mycroft-core/pull/1335
- add `ovos_utils.intents.ConverseTracker` 
	- enables https://github.com/MycroftAI/mycroft-core/pull/1468 (improved)

### Mycroft Patches

adds `òvos_utils.waiting_for_mycroft` which includes monkey patched alternative imports for mycroft-core

`MycroftSkill` and `FallbackSkill` patches:

- add `MycroftSkill.handle_skill_deactivated` from https://github.com/MycroftAI/mycroft-core/pull/1468 (improved)
- patch `MycroftSkill.bind` 
	- enable `SkillApi` from https://github.com/MycroftAI/mycroft-core/pull/1822
	- enable `ovos_utils.intents.ConverseTracker`
- patch `MycroftSkill.voc_match` https://github.com/MycroftAI/mycroft-core/pull/2675
- patch `MycroftSkill.gui` to use patched `SkillGUI` (see bellow)
- patch `MycroftSkill.init_dialog` to use `ovos_utils.lang.get_language_dir`
- patch `MycroftSkill.load_vocab_files` to use `ovos_utils.lang.get_language_dir`
- patch `MycroftSkill.load_regex_files` to use `ovos_utils.lang.get_language_dir`

```python
from ovos_utils.waiting_for_mycroft.base_skill import MycroftSkill
from ovos_utils.waiting_for_mycroft.base_skill import FallbackSkill
from ovos_utils.waiting_for_mycroft.skill_api import skill_api_method

class TestSkill(MycroftSkill):
    @skill_api_method
    def speak_meth(self, message):
        """Speak the test sentence."""
        self.speak('This is a test')
 
    @skill_api_method
    def speak_meth2(self, message):
        """Speak another test sentence."""
        self.speak('This is another test')

```

You can then use this skill from another skill

```python
from ovos_utils.waiting_for_mycroft.skill_api import SkillApi

# get an api object and use that to trigger the skill:
my_skill = SkillApi.get('myskill.forslund')
my_skill.speak_meth()
```

`SkillGUI` patches:

- patch `SkillGUI.show_pages` to use `ovos_utils.resolve_ovos_resource_file`
- patch `SkillGUI.remove_pages` to use `ovos_utils.resolve_ovos_resource_file`

Video playback from https://github.com/MycroftAI/mycroft-core/pull/2683
- add `SkillGUI.play_video`
- add `SkillGUI.is_video_displayed`
- add `SkillGUI.playback_status`
- add `SkillGUI.pause_video` 
- add `SkillGUI.resume_video`
- add `SkillGUI.stop_video`

Skill settings from https://github.com/MycroftAI/mycroft-core/pull/2698
- add `SkillGUI.register_settings` 
- add `SkillGUI.show_settings`

```python
from ovos_utils.waiting_for_mycroft.skil_gui import SkillGUI
```

`CommonPlaySkill` patches:
- add `CPSMatchType` from https://github.com/MycroftAI/mycroft-core/pull/2660
- patch `CommonPlaySkill.__init__`
- patch `CommonPlaySkill.__handle_play_query`
- patch `CommonPlaySkill.__handle_play_start`
- patch `CommonPlaySkill.CPS_match_query_phrase`
```python
from ovos_utils.waiting_for_mycroft.common_play import CPSMatchType
from ovos_utils.waiting_for_mycroft.common_play import CommonPlaySkill
```

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
How does the universal fallback work with auto-translation, is that going to get fed back into the intent parsers?

**Comment by JarbasAl** [comment]
that was just moved around and otherwise not touched by this PR, it's an old experiment and might require a review in follow up PR

it uses autotranslate in the speak method,and overrides intent register methods to also auto translate utterance, you will get rate limited quickly if abusing this

**Comment by JarbasAl** [comment]
still want to add https://github.com/MycroftAI/mycroft-core/pull/987

i'm testing all of these in the wild, but is almost merge ready

**Comment by JarbasAl** [comment]
shamelessly self merging for proper testing in the wild

**Comment by ChanceNCounter** [comment]
I have zero complaints in this case, but `pip3 install --force git+<>`

**Comment by JarbasAl** [comment]
but i wanna release skills using this, noone will test individual functionality, but maybe ill get issues in the downstream skills, so id rather have it properly packaged :p 

I am the only use in the wild of ovos_utils either way :man_shrugging:

**Pull request merged**
